name: Build and Deploy

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    name: Build Files
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Dependencies
      run: |
        cd scripts
        pip install -r requirements.txt
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Get Latest Files
      run: |
        python scripts/download.py
    - name: Install Deps
      run: |
        yarn install
    - name: Build Site
      run: |
        yarn build
    - name: Upload Artifacts 🔺
      uses: actions/upload-artifact@v1
      with:
          name: public
          path: public/
  deploy:
    name: Deploy Site
    needs: [build] # The second job must depend on the first one to complete before running, and uses ubuntu-latest instead of windows.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Download Artifacts 🔻 # The built project is downloaded into the 'site' folder.
        uses: actions/download-artifact@v1
        with:
          name: public
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
            BRANCH: gh-pages
            FOLDER: public
